################################################################
#
#
# Pipeline pipeline_rnaseqmismatches.py configuration file for sphinxreport
#
# This pipeline.ini file lists some configuration options that you might 
# want a user to set automatically.
#
# Add pipeline specific options into separate sections
#
################################################################

## general options


# Project name
projectname: ''

# Copyright statement
copyright: Sudbery Lab (2016)

# The short X.Y version.
version: 0.1

# The full version, including alpha/beta/rc tags.
release: 0.1

########################################################
# the genome to use (UCSC convention)
genome: hg38_noalt


#platform used to generate your data. Valid values: ILLUMINA, SOLID, LS454, HELICOS and PACBIO
platform: ILLUMINA

#group sample name
groupsample: SMA

#path to the plain fasta file for the chosen genome. Must have corresponding index (.fai) and dictionary (.dict) files, which can be made with samtools and picard respectively.
fasta: /shared/sudlab1/General/mirror/genomes/plain/

#path to the fasta file used to map the data
mapfasta: /shared/sudlab1/General/mirror/genomes/hisat/hg38_noalt.fa

#path to gtf file containing the relevant genes
gtf: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/ensembl.dir/geneset_all.gtf.gz


database:
    name: /shared/sudlab1/General/projects/GTEx_V6_rnaseq_SRA/lofreq
    ################################################################
    #
    # Location of annotation database
    #
    ################################################################
annotations:
    database: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85/csvdb

    # directory with annotation information
    dir: /shared/sudlab1/General/annotations/hg38_noalt_ensembl85

    ################################################################
    #
    # sphinxreport build options
    #
    ################################################################
report:

    # prefix to use for publishing the report from this pipeline
    prefix: default

